#pragma once
#define _CRT_SECURE_NO_WARNINGS

#include <windows.h>
#include <string>
#include <cstring>
#include <sstream>
#include <utility>
#include <limits.h>
#include <iostream>
#include <fstream>
#include <comdef.h>
#include <Wbemidl.h>
#include <vector>
#include <string>
#include <sysinfoapi.h>
#include <windows.h>
#include <stdio.h>
#include <thread>
#include <wincrypt.h>
#include <iterator>
#include <sstream>
#include <cstring>
#include <chrono>
#include <ctime>
#include <time.h>
#include <random>
#include <future>